# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeployKeychain < Formula
  desc "Command-line tool to permit the easy usage of multiple GitHub deploy keys simultaneously."
  homepage "https://github.com/nint8835/deploy-keychain"
  version "1.0.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/nint8835/deploy-keychain/releases/download/v1.0.0/deploy-keychain_1.0.0_macos_amd64.tar.gz"
    sha256 "96976ca2707ff3a5249fbc7ea14fdfabbdf8b8f299d27e788ca7ca84a3ff171a"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/nint8835/deploy-keychain/releases/download/v1.0.0/deploy-keychain_1.0.0_macos_arm64.tar.gz"
    sha256 "7de56245b974ba3ef596470e9ae7fd09906efaa0ece003c540a96c464ff8fbd6"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nint8835/deploy-keychain/releases/download/v1.0.0/deploy-keychain_1.0.0_linux_amd64.tar.gz"
    sha256 "52010e2b335ef612b027d0f892e3731113af6f9713b97d611b5269fb9522099e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nint8835/deploy-keychain/releases/download/v1.0.0/deploy-keychain_1.0.0_linux_arm64.tar.gz"
    sha256 "973a24fb7f8be44da11a9489455c6d4681d456b5796687fb785697a485b24e86"
  end

  def install
    bin.install "deploy-keychain"
  end
end
