# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeployKeychain < Formula
  desc "Command-line tool to permit the easy usage of multiple GitHub deploy keys simultaneously."
  homepage "https://github.com/nint8835/deploy-keychain"
  version "1.0.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/nint8835/deploy-keychain/releases/download/v1.0.0/deploy-keychain_1.0.0_macos_amd64.tar.gz"
    sha256 "e02f06d5e075bbc4523d8ee00f0d73a73ee82cd5a208ec6fb87488dd2c58f253"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/nint8835/deploy-keychain/releases/download/v1.0.0/deploy-keychain_1.0.0_macos_arm64.tar.gz"
    sha256 "355fc459f3b1fec9701a541830ced1a0a54774fc198720d8aebce9038dfc2bf7"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nint8835/deploy-keychain/releases/download/v1.0.0/deploy-keychain_1.0.0_linux_amd64.tar.gz"
    sha256 "1f7ee4f299c834ac4d00e6dece460762c938d9b96424c695811d47d2cb15986c"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nint8835/deploy-keychain/releases/download/v1.0.0/deploy-keychain_1.0.0_linux_arm64.tar.gz"
    sha256 "3eb5606eda217c387bd052e845d204807410414b74d73e33063265b1c094f6f0"
  end

  def install
    bin.install "deploy-keychain"
  end
end
